### ISSUE TITLE
Proccess starts from the beginning

### ISSUE THREAD

**Issue by dnish** [capriza/socketgd#4]
Hey,
I've tried to use the package for handling the proccess of a transaction. In our case, we want to resend proccess updates if the user's connection has been interrupted for a moment (server emits events). I've tried to disable WLAN for 10 seconds and enabled it again, but instead of receiving all "lost" messages, the proccess starts from the beginning. 

The client get's connected to the same instance after reconnect.

**Comment by fujifish** [comment]
> the proccess starts from the beginning

Do you mean that all messages get re-transmitted from the server to the client from the beginning starting from the first message?

**Comment by dnish** [comment]
Nope, the client starts emitting the first event again. For example, we creating the socket connection within a function callback and then send an emit to the server

    this.socket.emit("start");
    this.socket.on("update", (obj) => { ... });


If I disconnect and then connect again, the "start" event is fired again and everything begins from the start.

**Comment by fujifish** [comment]
Are you calling the `ack()` method on the server side?
In order for a message/event not to be re-sent, the receiver must `ack` it, like so:

```javascript
  socketgd.on('start', function(data, ack, msgId) {
    // finished handling the start event, ack it
    ack();
  });
```

**Comment by dnish** [comment]
Ah thanks, I'll try that. Think I only tried that with the "normal" Socket.IO, I'll give you feedback after testing.

**Comment by dnish** [comment]
Mh, in this case nothings happens after reconnecting, the progress slider stays at the position, so the messages weren't received.

**Comment by dnish** [comment]
Okay, I got the problem - I did define my socketGD object within the connection event on the server side, I had to put it on the top of the file.

But now I'm just wondering, how do you seperate between different sockets if I fire an event?

**Comment by fujifish** [comment]
Every time a new connection is received on the server side, wrap it (the new socket) with a new SocketGD object to track the messages and acks that flow through it.

**Comment by dnish** [comment]
Yeah, I tried that, but then nothing happens. It only works (one time) if I define it outside of the <code>io.on('connection')</code>.

**Comment by fujifish** [comment]
I've misled you.
On the server side, whenever a socket _reconnects_, the `connection` event is fired providing a new `socket` object. However since it represents the same client in actuality, you need to _reuse_ an existing SocketGD object that already contains the `lastAcked` message and give it the new socket via the `setSocket` method. It's up to you to identity if the client is new or a reconnecting one and to know which (previously created) SocketGD object to use.
You can also create a new SocketGD object to wrap the new socket and call `setLastAcked`.

Take a look at the test "sends and receives messages after disconnect" for an example.
