### ISSUE TITLE
socketgd.setSocket(newSocket)

### ISSUE THREAD

**Issue by scramble45** [capriza/socketgd#5]
In the example you mention:

````
socketgd.setSocket(newSocket)
````

Do you mean just "socket" in place of newSocket? Just trying to understand your example fully this is what I currently have:

````
//Server:
var SocketGD = require('socketgd').SocketGD;
var socketgd = new SocketGD();
var io = require('socket.io')(1984);

// socket.io server
io.on('connection', function(socket) {

  // set the underlying socket in socketgd.
  // if any already acked messages arrive they will be silently discarded
  socketgd.setSocket(socket);

  socketgd.on('message', function(message, ack, msgId) {
    console.log('Got message ' + message + ' with id ' + msgId);
    // finished handling the message, ack it
    ack();
  });

  socketgd.on('my-event', function(data, ack, msgId) {
    console.log('Got my-event ' + data.hi + ' with id ' + msgId);
    // finished handling the event, ack it
    ack();
  });

});
````

````
//Client:
var io = require('socket.io-client');
var SocketGD = require('socketgd').SocketGD;

var  host = 'http://localhost:1984';
// create the socket.io socket
var socket = io(host);

// wrap the socket with socketgd
var socketgd = new SocketGD(socket);

// use socketgd instead of the socket
socketgd.on('connect', function() {
  console.log("I'm connected!");
});

setInterval(function(){  
	socketgd.send('I am sending you a message');
	socketgd.emit('my-event', {hi: 'there'});
}, 1200);
// ...lets assumes the socket gets disconnected before receiving an ack for 'your-event'
// and we created a new socket...

// set the new socket.
// the un-acked 'your-event' message will be silently sent again
socketgd.setSocket(socket);
````

**Comment by scramble45** [comment]
I also plan on having multiple clients to the same server that can disconnect/reconnect at anytime. This example doesn't seem to do that any thoughts?

**Comment by fujifish** [comment]
Your example seems to be correct. Setting the socket should re-send any pending messages that have not been acked yet.
If the server has in fact acked the message before the client is aware of it due to disconnection, upon reconnection it will send the message again, however the server will silently discard the message since it has already acked it.

For the record, we are using socketgd in production in conjunction with a message relaying service built on top of node-busmq.
In order to handle multiple clients in the server side, we associate a connecting client with a single SocketGD instance, so that upon reconnection we can re-associate the newly connected socket.io socket with the same SocketGD object (which may still be holding un-acked messages). 

Can you provide a real example that reproduces the problem of the client not getting the messages?

**Comment by scramble45** [comment]
All I was doing was running the server locally and the client locally I would then disconnect the client from the server at some point and wait ten minutes then launch the client script again. Upon doing so I would get the connected message on the client side but no messages never got to the server TMK. Seems too be inconsistent sometimes it will pickup where it left off. I'm particularly interested in using socketgd with node-busmq do you have any examples of this? Does the redis db run on the server or the client side?

**Comment by fujifish** [comment]
If you terminated the client and relaunched, it would restart the internal msg id counter from 0 (on the client side). If the server has acked any messages, any messages with ID lower than the last one that the server acked would get silently discarded. Only when messages with a higher-than-last-acked message id would start arriving, would the server start receiving them.
